# server
server:
  port: 8888

# 图片文件下载
ftp:
  host: 111.230.195.169   # FTP服务器ip地址
  port: 21                # FTP服务器端口
  username: ftproot       # FTP登录账号
  password: 8uFYnRPnbpJ1  # FTP登录密码
  filePath: picture       # FTP服务器文件存放路径

# spring配置
spring:
  profiles: prod # 配置生产环境
  thymeleaf: # 关闭thymeleaf缓存
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # druid配置
      #=== 数据库配置 - 基本连接信息 ===#
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: OSOPW1wQVbvh.
      url: jdbc:mysql://111.230.195.169:3306/cakeshop?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
      #=== 连接池配置 ===#
      initialSize: 5    # 初始化连接个数
      minIdle: 5        # 最小空闲连接个数
      maxActive: 20     # 最大连接个数
      maxWait: 60000    # 获取连接时最大等待时间，单位毫秒。
      timeBetweenEvictionRunsMillis: 60000   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000     # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL    # 用来检测连接是否有效的sql，要求是一个查询语句。
      testWhileIdle: true       # 建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false       # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false       # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: true    #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: 20     #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      filters: stat,wall,log4j        # 配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      useGlobalDataSourceStat: true   # 合并多个DruidDataSource的监控数据
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  mvc:
    favicon:
      enabled: false

# 整合Mybatis
mybatis:
  type-aliases-package: com.cyan.pojo            # 配置别名
  mapper-locations: classpath:mapper/*.xml       # mapper.xml配置文件

# Mybatis分页插件
pagehelper:
  helperDialect: mysql      # 数据库
  reasonable: false         # 是否分页合理化
  rowBoundsWithCount: true  # 是否进行count查询
  offsetAsPageNum: true     # 是否将参数offset作为PageNum使用